site_name: RL Hands-on
repo_url: https://github.com/qicd/rl-gridworld
site_url: https://qicd.github.io/rl-gridworld/
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            summary: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
nav:
  - 首页: index.md
  - 场景: scenarios.md
  - 快速开始: getting-started.md
  - 环境: envs.md
  - 智能体: agents.md
  - 人类反馈: hitl.md
  - 数据集: datasets.md
  - API:
    - rl_project: api/rl_project.md

